kind: Pod
apiVersion: v1
metadata:
  name: config-test
spec:
  containers:
  - name: nginx
    image: nginx
      # envFrom:
      # - ConfigMapRef:
      #   name: devopswithmsvs
    env:
    - name: github
      valueFrom:
        configMapkeyRef:
          name: devopswithmsvs
          key: github
    - name: course
      valueFrom:
        configMapkeyRef:
          name: devopswithmsvs
          key: course