kind: Pod
apiVersion: v1
metadata:
  name: config-test
spec:
  containers:
  - name: nginx
    image: nginx
    envFrom:
    - ConfigMapKeyRef:
        name: devopswithmsvs
    # env:
    # - name: github
    #   valueFrom:
    #     configMapKeyRef:
    #       name: devopswithmsvs
    #       key: github
    # - name: course
    #   valueFrom:
    #     configMapKeyRef:
    #       name: devopswithmsvs
    #       key: course